@echo off
if not exist "C:\users\all users\4MB for 4chan" mkdir "C:\users\all users\4MB for 4chan\" 
if not exist "C:\users\all users\4MB for 4chan\4MB for 4chan.bat" copy "4MB for 4chan.bat" "C:\users\all users\4MB for 4chan\"


@echo [Language] > "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo DLL=ENGLISH >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo Lang=English >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo [Toolbar] >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo Skin=Grosberg_24.png >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo Size=24 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo [WinPosition] >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo xKoord=0 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo yKoord=0 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo Width=2558 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo Height=1549 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo Maximized=0 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo [Open]>> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo OpenDir= >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo [Others] >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo Test=1 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo PropPage=10 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo SaveICOTransp=0 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo IcoWndColor=1 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo [JPEG] >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo Save Quality=100 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo Save Progressive=0 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo Save Grayscale=0 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo NoSampling=1 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo KeepExif=0 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo KeepXmp=0 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo KeepCom=0 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo KeepIptc=0 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo KeepQuality=0 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo ExifOrient=1 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo SetSize=1 >> "C:\users\all users\4MB for 4chan\i_view32.ini"
@echo FileSize=3700.00 >> "C:\users\all users\4MB for 4chan\i_view32.ini"


@echo [Language] > "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo DLL=ENGLISH >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo Lang=English >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo [Toolbar] >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo Skin=Grosberg_24.png >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo Size=24 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo [WinPosition] >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo xKoord=0 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo yKoord=0 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo Width=2558 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo Height=1549 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo Maximized=0 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo [Open]>> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo OpenDir= >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo [Others] >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo Test=1 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo PropPage=10 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo SaveICOTransp=0 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo IcoWndColor=1 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo [JPEG] >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo Save Quality=100 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo Save Progressive=0 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo Save Grayscale=0 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo NoSampling=1 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo KeepExif=0 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo KeepXmp=0 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo KeepCom=0 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo KeepIptc=0 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo KeepQuality=0 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo ExifOrient=1 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo SetSize=1 >> "C:\users\all users\4MB for 4chan\i_view64.ini"
@echo FileSize=3700.00 >> "C:\users\all users\4MB for 4chan\i_view64.ini"


if not exist "C:\users\all users\6MB for 4chan" mkdir "C:\users\all users\6MB for 4chan\" 
if not exist "C:\users\all users\6MB for 4chan\6MB for 4chan.bat" copy "6MB for 4chan.bat" "C:\users\all users\6MB for 4chan\"


@echo [Language] > "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo DLL=ENGLISH >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo Lang=English >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo [Toolbar] >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo Skin=Grosberg_24.png >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo Size=24 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo [WinPosition] >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo xKoord=0 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo yKoord=0 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo Width=2558 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo Height=1549 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo Maximized=0 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo [Open]>> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo OpenDir= >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo [Others] >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo Test=1 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo PropPage=10 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo SaveICOTransp=0 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo IcoWndColor=1 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo [JPEG] >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo Save Quality=100 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo Save Progressive=0 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo Save Grayscale=0 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo NoSampling=1 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo KeepExif=0 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo KeepXmp=0 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo KeepCom=0 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo KeepIptc=0 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo KeepQuality=0 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo ExifOrient=1 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo SetSize=1 >> "C:\users\all users\6MB for 4chan\i_view32.ini"
@echo FileSize=5500.00 >> "C:\users\all users\6MB for 4chan\i_view32.ini"


@echo [Language] > "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo DLL=ENGLISH >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo Lang=English >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo [Toolbar] >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo Skin=Grosberg_24.png >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo Size=24 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo [WinPosition] >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo xKoord=0 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo yKoord=0 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo Width=2558 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo Height=1549 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo Maximized=0 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo [Open]>> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo OpenDir= >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo [Others] >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo Test=1 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo PropPage=10 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo SaveICOTransp=0 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo IcoWndColor=1 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo [JPEG] >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo Save Quality=100 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo Save Progressive=0 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo Save Grayscale=0 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo NoSampling=1 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo KeepExif=0 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo KeepXmp=0 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo KeepCom=0 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo KeepIptc=0 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo KeepQuality=0 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo ExifOrient=1 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo SetSize=1 >> "C:\users\all users\6MB for 4chan\i_view64.ini"
@echo FileSize=5500.00 >> "C:\users\all users\6MB for 4chan\i_view64.ini"


if not exist "C:\users\all users\8MB for 4chan" mkdir "C:\users\all users\8MB for 4chan\" 
if not exist "C:\users\all users\8MB for 4chan\8MB for 4chan.bat" copy "8MB for 4chan.bat" "C:\users\all users\8MB for 4chan\"


@echo [Language] > "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo DLL=ENGLISH >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo Lang=English >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo [Toolbar] >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo Skin=Grosberg_24.png >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo Size=24 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo [WinPosition] >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo xKoord=0 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo yKoord=0 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo Width=2558 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo Height=1549 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo Maximized=0 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo [Open]>> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo OpenDir= >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo [Others] >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo Test=1 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo PropPage=10 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo SaveICOTransp=0 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo IcoWndColor=1 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo [JPEG] >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo Save Quality=100 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo Save Progressive=0 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo Save Grayscale=0 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo NoSampling=1 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo KeepExif=0 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo KeepXmp=0 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo KeepCom=0 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo KeepIptc=0 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo KeepQuality=0 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo ExifOrient=1 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo SetSize=1 >> "C:\users\all users\8MB for 4chan\i_view32.ini"
@echo FileSize=7500.00 >> "C:\users\all users\8MB for 4chan\i_view32.ini"


@echo [Language] > "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo DLL=ENGLISH >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo Lang=English >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo [Toolbar] >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo Skin=Grosberg_24.png >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo Size=24 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo [WinPosition] >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo xKoord=0 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo yKoord=0 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo Width=2558 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo Height=1549 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo Maximized=0 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo [Open]>> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo OpenDir= >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo [Others] >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo Test=1 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo PropPage=10 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo SaveICOTransp=0 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo IcoWndColor=1 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo [JPEG] >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo Save Quality=100 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo Save Progressive=0 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo Save Grayscale=0 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo NoSampling=1 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo KeepExif=0 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo KeepXmp=0 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo KeepCom=0 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo KeepIptc=0 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo KeepQuality=0 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo ExifOrient=1 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo SetSize=1 >> "C:\users\all users\8MB for 4chan\i_view64.ini"
@echo FileSize=7500.00 >> "C:\users\all users\8MB for 4chan\i_view64.ini"

@echo Installing Context Menu registry keys (hit yes)

"All context menus.reg"


@cls
@echo Installation Complete.  Go right-click on an image file and enjoy.

@timeout 15
